import os
import pandas as pd
import streamlit as st

from utils.config import DATA_PATH
from utils.preprocessing import load_artifacts, predict, artifacts_exist
from utils.health_score import compute_health_score
from utils import visualization as viz

st.set_page_config(page_title="Student Analysis", page_icon="🧑‍🎓", layout="wide")
st.title("🧑‍🎓 Individual Student Analysis")


@st.cache_data
def load_dataset():
    if not os.path.exists(DATA_PATH):
        return None
    return pd.read_csv(DATA_PATH)


df = load_dataset()
if df is None:
    st.warning(f"No dataset found at `{DATA_PATH}`. Add your dataset to unlock this page.")
    st.stop()

id_col = "id" if "id" in df.columns else None
if id_col:
    selected_id = st.selectbox("Select a student", df[id_col].tolist())
    student = df[df[id_col] == selected_id].iloc[0]
else:
    idx = st.selectbox("Select a student (row index)", df.index.tolist())
    student = df.loc[idx]

st.divider()

profile_fields = [
    ("heart_rate", "Heart Rate"),
    ("bmi", "BMI"),
    ("sleep_duration", "Sleep Duration"),
    ("sleep_quality", "Sleep Quality"),
    ("stress_level", "Stress Level"),
    ("step_count", "Step Count"),
    ("exercise_duration", "Exercise Duration"),
    ("water_intake", "Water Intake"),
    ("calorie_expenditure", "Calorie Expenditure"),
    ("diet_type", "Diet Type"),
    ("physical_activity_level", "Physical Activity Level"),
    ("gender", "Gender"),
    ("smoking_alcohol", "Smoking / Alcohol"),
]
available_fields = [(c, label) for c, label in profile_fields if c in df.columns]

left, right = st.columns([2, 1])

with left:
    st.subheader("Health Profile")
    profile_cols = st.columns(3)
    for i, (col, label) in enumerate(available_fields):
        val = student[col]
        display_val = f"{val:.1f}" if isinstance(val, float) else str(val)
        profile_cols[i % 3].metric(label, display_val)

with right:
    st.subheader("Student Health Score")
    score_inputs = {c: student[c] for c, _ in available_fields if c in [
        "sleep_duration", "step_count", "exercise_duration", "water_intake",
        "heart_rate", "bmi", "stress_level"
    ]}
    score = compute_health_score(score_inputs)
    if score is not None:
        st.plotly_chart(viz.gauge_chart(score), use_container_width=True)
    st.caption(
        "⚠️ This is a simple, transparent dashboard indicator computed from the student's "
        "raw inputs — **not** a medical diagnosis. See the README for the exact formula."
    )

st.divider()

st.subheader("AI Predicted Health Risk")
if "health_condition" in df.columns:
    st.markdown(f"**Recorded label in dataset:** `{student['health_condition']}`")

if artifacts_exist():
    model, prep = load_artifacts()
    row_df = pd.DataFrame([student.drop(labels=["health_condition"], errors="ignore")])
    try:
        labels, confidence, proba_df = predict(row_df, model, prep)
        pred = labels[0]
        conf = confidence[0] if confidence is not None else None

        c1, c2 = st.columns(2)
        c1.metric("AI Predicted Category", pred.upper())
        if conf is not None:
            c2.metric("Prediction Confidence", f"{conf*100:.1f}%")
        if proba_df is not None:
            st.markdown("**Class probabilities**")
            st.bar_chart(proba_df.T)
    except Exception as e:
        st.error(f"Could not generate a prediction for this student: {e}")
else:
    st.info(
        "No trained model found yet. Run `python train_model.py` to enable AI risk "
        "prediction for individual students."
    )

st.caption(
    "This prediction is generated by a machine learning model trained on this dataset. "
    "It is for educational and analytical purposes only and is not a medical diagnosis."
)
